### ISSUE TITLE
Correctness of BA-Shape Evaluation

### ISSUE THREAD

**Issue by alexbui91** [EnyanDai/SEGNN#1]
Dear Mr.  Enyan Dai,

My name is Alex from Seoul National University. I want to compare your model results with my current work. When I look into your implementation for BA-Shape training and evaluation, I think the evaluation part is incorrect.

```
real = []
for i in range(edge_index.shape[1]):
    real.append(edge_label_index[edge_index[0,i],edge_index[1,i]])
```

The code tells that you append edges in edge_index to real_labels. However, it seems that edge_index is extracted via the k_hop_subgraph function in the subgraph.py file. When I print out the "real" array, most of the time, the result is like [0.0, 1.0, 1.0, 1.0, 1.0], which is not accurate, in my opinion. According to PGExplainer and GNNExplainer, the ground-truth explanation should include all five edges constructing the house motif. 

I suggest that the real graph for a node should be [n, n+1, n+2, n+3, n+4], given that n is the targeted explanation node. Since the first 400 nodes (0=>399) are in BA graphs, nodes with indices 400, 405, ... are the starting index of a house motif when generating a BA-Shape graph.

Please correct me if I am wrong and hope to hear from you soon.

Bests,
Thank you,

**Comment by EnyanDai** [comment]
Hi,

Thanks very much for your interests to our work. I agree with you that a using [n, n+1, n+2, n+3, n+4] for the evaluation on BA-shape could be better. We do this is simply based on the experimental setting in PGExplainer and GNNExplainer. And you can find setting in their codes here: https://github.com/flyingdoog/PGExplainer/blob/master/BA-shapes.ipynb

Bests,
Enyan
